[package]
name = "aoeworld-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
aoe-assets = { path = "../crates/assets" }
aoe-map = { path = "../crates/map" }
serde_json = "1.0"
libfuzzer-sys = "=0.4.10"

[workspace]

[[bin]]
name = "drs"
path = "fuzz_targets/drs.rs"
test = false
doc = false
bench = false

[[bin]]
name = "slp"
path = "fuzz_targets/slp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "palette"
path = "fuzz_targets/palette.rs"
test = false
doc = false
bench = false

[[bin]]
name = "manifest"
path = "fuzz_targets/manifest.rs"
test = false
doc = false
bench = false

[[bin]]
name = "map_package"
path = "fuzz_targets/map_package.rs"
test = false
doc = false
bench = false

[[bin]]
name = "environment_page"
path = "fuzz_targets/environment_page.rs"
test = false
doc = false
bench = false

[[bin]]
name = "map_chunk"
path = "fuzz_targets/map_chunk.rs"
test = false
doc = false
bench = false
